import {
  LucideIcon,
  PiggyBank,
  CreditCard,
  LayoutDashboard,
  BarChart,
  Tag,
  Settings,
  Wallet,
  Sun,
  Moon,
  Laptop,
  User,
  X,
  Home,
  Car,
  Coffee,
  ShoppingCart,
  Plane,
  ReceiptEuro,
  HeartPulse,
  Shirt,
  GraduationCap,
  BriefcaseBusiness,
  HandCoins,
  Clapperboard,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Wallet,
  dashboard: LayoutDashboard,
  transactions: CreditCard,
  investments: BarChart,
  budgets: PiggyBank,
  categories: Tag,
  setting: Settings,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  user: User,
  close: X,
  home: Home,
  transportation: Car,
  restaurant: Coffee,
  grocery: ShoppingCart,
  travel: Plane,
  bill: ReceiptEuro,
  health: HeartPulse,
  personal: Shirt,
  education: GraduationCap,
  business: BriefcaseBusiness,
  subscription: Clapperboard,
  misc: HandCoins,
};
